---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bombastik/public_html
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
    - /bin/cp -R old $DEPLOYPATH
    - /bin/cp -R 3d $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    